prompt: "como fazer swap na jetson orin"

models_to_test:

  - deepseek-r1:1.5b
  - gemma3:4b
  - gemma3:1b
  - llama3.2:1b
  - llama3.2:3b

swap_configurations:
  - "enabled"


power_modes:
  - "0"

output_csv_file: "results/benchmark.csv"
